/*
 * Copyright (C) 2013 Shubham Rao
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package caesarCipher;

/**
 *
 * @author shubham
 */
public class CaesarCipherUI extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form NewJFrame
     */
    public CaesarCipherUI() {
        initComponents();
    }
    
    /**
     *
     * @param sourceText
     * @param shift
     * @return
     */
    public String encryptText(String sourceText, int shift){
        StringBuilder encryptedText= new StringBuilder();
        char sourceTextArray[] = sourceText.toCharArray();
        for (char character:sourceTextArray){
            char shiftedCharacter = character;
            shiftedCharacter+= (char)shift;
            encryptedText.append(shiftedCharacter);
        }
        return encryptedText.toString();
    }
    
    /**
     *
     * @param sourceText
     * @param shift
     * @return
     */
    public String decryptText(String sourceText, int shift){
        StringBuilder decryptedText= new StringBuilder();
        char sourceTextArray[] = sourceText.toCharArray();
        for (char character:sourceTextArray){
            char shiftedCharacter = character;
            shiftedCharacter-= (char)shift;
            decryptedText.append(shiftedCharacter);
        }
        return decryptedText.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        decryptedText_label = new javax.swing.JLabel();
        shift = new javax.swing.JTextField();
        shift_label = new javax.swing.JLabel();
        decryptedText_pane = new javax.swing.JScrollPane();
        decryptedText = new javax.swing.JTextArea();
        encryptedText_label = new javax.swing.JLabel();
        encryptedtText_pane = new javax.swing.JScrollPane();
        encryptedText = new javax.swing.JTextArea();
        encryptDecrypt_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        setName("caesarCipher"); // NOI18N

        decryptedText_label.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("caesarCipher/Bundle"); // NOI18N
        decryptedText_label.setText(bundle.getString("ENTER THE TEXT:")); // NOI18N

        shift_label.setText(bundle.getString("ENTER THE SHIFT TO USE")); // NOI18N

        decryptedText.setColumns(20);
        decryptedText.setRows(5);
        decryptedText_pane.setViewportView(decryptedText);

        encryptedText_label.setText(bundle.getString("ENCRYPTED TEXT:")); // NOI18N

        encryptedText.setColumns(20);
        encryptedText.setRows(5);
        encryptedtText_pane.setViewportView(encryptedText);

        encryptDecrypt_button.setText(bundle.getString("ENCRYPT/DECRYPT")); // NOI18N
        encryptDecrypt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptDecrypt_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(encryptedtText_pane))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(encryptedText_label)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(decryptedText_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                                .addComponent(shift_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shift, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(encryptDecrypt_button))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(decryptedText_pane)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shift_label)
                    .addComponent(shift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decryptedText_label))
                .addGap(6, 6, 6)
                .addComponent(decryptedText_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(encryptedText_label)
                .addGap(12, 12, 12)
                .addComponent(encryptedtText_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(encryptDecrypt_button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptDecrypt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptDecrypt_buttonActionPerformed
        // TODO add your handling code here:
        encryptedText.setText(encryptText(decryptedText.getText(), 
                              Integer.parseInt(shift.getText())));
        //decryptedText.setText(decryptText(encryptedText.getText(), 
        //                      Integer.parseInt(shift.getText())));
    }//GEN-LAST:event_encryptDecrypt_buttonActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (java.util.ResourceBundle.getBundle("test/Bundle").getString("NIMBUS").equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaesarCipherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaesarCipherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaesarCipherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaesarCipherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CaesarCipherUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea decryptedText;
    private javax.swing.JLabel decryptedText_label;
    private javax.swing.JScrollPane decryptedText_pane;
    private javax.swing.JButton encryptDecrypt_button;
    private javax.swing.JTextArea encryptedText;
    private javax.swing.JLabel encryptedText_label;
    private javax.swing.JScrollPane encryptedtText_pane;
    private javax.swing.JTextField shift;
    private javax.swing.JLabel shift_label;
    // End of variables declaration//GEN-END:variables
}
